// Builds app/lara.css from PrimeReact's Lara theme, run before dev and build.
// 1. Lara v10 hard-codes its colours (no var(--primary-color) in component rules), so they are
//    rewritten onto the brand tokens in app/globals.css. Those tokens switch with data-theme, so
//    this one file serves light and dark: no second stylesheet, nothing swapped at runtime.
// 2. Only rules for components the site renders are kept. The full theme is 230KB of rules for
//    ~90 components, and recalculating it cost ~600ms on a throttled phone before first paint.
//    Using a new PrimeReact component? Add it to USED.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const USED = new Set(
  "button menu menuitem submenu tabview tag tooltip ripple ink component link disabled focus highlight hidden connected toggleable icon".split(" "),
);
// A selector survives only if every .p-* class in it belongs to a component we render, so
// `.p-splitbutton .p-button` goes even though it mentions a button.
const ours = (selector) => {
  const words = [...selector.matchAll(/\.p-([a-z]+)/g)].map((m) => m[1]);
  return words.length > 0 && words.every((w) => USED.has(w));
};

const colours = [
  [/rgba\(20, 184, 166, [\d.]+\)/g, "var(--glow)"],
  ["#14b8a6", "var(--accent)"],
  ["#0d9488", "var(--accent-hover)"],
  ["#0f766e", "var(--accent)"],
  ["#99f6e4", "var(--accent-2)"],
  ["#f0fdfa", "var(--surface-2)"],
  ["#ffffff", "var(--surface)"],
  ["#4b5563", "var(--ink-soft)"],
  ["#374151", "var(--text)"],
  ["#6b7280", "var(--muted)"],
  ["#e5e7eb", "var(--border)"],
  ["#d1d5db", "var(--border-strong)"],
  ["#f3f4f6", "var(--surface-2)"],
  ["#f9fafb", "var(--bg)"],
];

const src = readFileSync("node_modules/primereact/resources/themes/lara-light-teal/theme.css", "utf8").split(/\r?\n/);

// Lara's shape: a :root block, two Inter @font-face blocks, then `@layer primereact { ... }` whose
// rules each open at a two-space indent and close on a line that is exactly "  }".
const root = src.slice(0, src.indexOf("}") + 1);
const layerStart = src.findIndex((l) => l.startsWith("@layer primereact"));
if (root[0] !== ":root {" || layerStart < 0) throw new Error("Lara theme layout changed; update scripts/themes.mjs");

const kept = [];
let block = null;
for (const line of src.slice(layerStart + 1)) {
  if (block) {
    block.push(line);
    if (line === "  }") {
      const text = block.join("\n");
      const brace = text.indexOf("{");
      if (text.startsWith("  @keyframes")) kept.push(text);
      else if (text.startsWith("  @")) {
        if (ours(text)) kept.push(text); // @media: keep only if everything inside is ours
      } else {
        const selectors = text.slice(0, brace).split(",").map((s) => s.trim()).filter(ours);
        if (selectors.length) kept.push(`  ${selectors.join(",\n  ")} ${text.slice(brace)}`);
      }
      block = null;
    }
  } else if (/^  \S/.test(line) && line !== "  }") block = [line];
}

let css = [...root, "@layer primereact {", ...kept, "}", ""].join("\n");
for (const [from, to] of colours) css = css.replaceAll(from, to);

mkdirSync("app", { recursive: true });
writeFileSync("app/lara.css", `/* Generated by scripts/themes.mjs from primereact Lara (MIT). Do not edit. */\n${css}`);
console.log(`app/lara.css: kept ${kept.length} rules, ${Math.round(css.length / 1024)}KB`);
